#!/usr/bin/env python3
"""Generate real Colab notebooks with the Python source embedded in cells.

The notebooks do not call `%run` on repository .py files. Each notebook contains
its corresponding source code directly, uses the inline matplotlib backend, and
adds a final display cell that renders generated PNG figures in the notebook.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "colab"


def notebook_for(src: Path) -> dict:
    code = src.read_text(encoding="utf-8")
    # In a notebook, do not force the non-interactive Agg backend.
    code = code.replace('matplotlib.use("Agg")', '# Colab/Jupyter uses the inline backend')
    code = code.replace("matplotlib.use('Agg')", "# Colab/Jupyter uses the inline backend")

    stem = src.stem
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"# {stem}\n",
                "\n",
                "Google Colab version with the implementation embedded directly in the notebook. ",
                "Plots and generated figures are displayed inline after execution.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "%matplotlib inline\n",
                "!pip -q install numpy matplotlib pandas dimod dwave-neal ortools\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": code.splitlines(keepends=True),
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Figures produced by this notebook\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "from IPython.display import display, Image\n",
                "pngs = sorted(Path('.').rglob('*.png'))\n",
                "if not pngs:\n",
                "    print('No PNG output was generated by this program.')\n",
                "for p in pngs:\n",
                "    print(p)\n",
                "    display(Image(filename=str(p)))\n",
            ],
        },
    ]
    return {
        "cells": cells,
        "metadata": {
            "colab": {"name": f"{stem}.ipynb", "provenance": []},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.x"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    OUT.mkdir(exist_ok=True)
    expected = set()
    for src in sorted(SRC.glob("*.py")):
        dst = OUT / f"{src.stem}.ipynb"
        dst.write_text(json.dumps(notebook_for(src), indent=2) + "\n", encoding="utf-8")
        expected.add(dst.name)
    for old in OUT.glob("*.ipynb"):
        if old.name not in expected:
            old.unlink()
    print(f"Generated {len(expected)} embedded-source Colab notebooks.")


if __name__ == "__main__":
    main()
