#!/usr/bin/env python3
"""Generate notebook-native Colab files with embedded primary source.

Each notebook embeds its corresponding src/*.py implementation directly in a
code cell. A lightweight setup cell clones the repository only so shared helper
modules and data remain importable. The primary program is never executed with
%run. A separate compatibility cell defines __file__ before the implementation
cell executes, preserving valid placement of any ``from __future__`` imports.

The generator validates every produced notebook for JSON structure, one-to-one
coverage of src/*.py, absence of %run wrappers, a notebook-safe __file__ value,
and Python syntax of the embedded implementation.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "colab"
REPO_DIR = "/content/uav-hubo-qiml-2026"


def notebook_for(src: Path) -> dict:
    code = src.read_text(encoding="utf-8")
    code = code.replace('matplotlib.use("Agg")', '# Colab/Jupyter uses the inline backend')
    code = code.replace("matplotlib.use('Agg')", "# Colab/Jupyter uses the inline backend")

    stem = src.stem
    embedded_path = f"{REPO_DIR}/src/{src.name}"
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"# {stem}\n",
                "\n",
                "Notebook-native Google Colab version. The primary implementation is embedded directly below. ",
                "The repository is cloned only to provide shared helper modules and data files. Figures are displayed inline.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "%matplotlib inline\n",
                "import os, sys\n",
                f"REPO_DIR = '{REPO_DIR}'\n",
                "if not os.path.isdir(REPO_DIR):\n",
                "    !git clone -q https://github.com/alimohammadi44/uav-hubo-qiml-2026.git {REPO_DIR}\n",
                "%cd /content/uav-hubo-qiml-2026\n",
                "!pip -q install -r requirements.txt\n",
                "SRC_DIR = os.path.join(REPO_DIR, 'src')\n",
                "if SRC_DIR not in sys.path:\n",
                "    sys.path.insert(0, SRC_DIR)\n",
                "print('Colab environment ready:', REPO_DIR)\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Notebook compatibility for scripts that resolve paths from __file__.\n",
                f"__file__ = r'{embedded_path}'\n",
                "print('Notebook source path:', __file__)\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Implementation\n", "The code in this cell is the actual implementation, not a `%run` wrapper.\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": code.splitlines(keepends=True),
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Figures produced by this notebook\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "from IPython.display import display, Image\n",
                "candidate_roots = [Path(REPO_DIR) / 'src' / 'outputs', Path(REPO_DIR) / 'outputs', Path('.')]\n",
                "pngs = []\n",
                "seen = set()\n",
                "for root in candidate_roots:\n",
                "    if root.exists():\n",
                "        for p in sorted(root.rglob('*.png')):\n",
                "            key = str(p.resolve())\n",
                "            if key not in seen:\n",
                "                seen.add(key)\n",
                "                pngs.append(p)\n",
                "if not pngs:\n",
                "    print('No PNG output was generated by this notebook.')\n",
                "for p in pngs:\n",
                "    print(p)\n",
                "    display(Image(filename=str(p)))\n",
            ],
        },
    ]
    return {
        "cells": cells,
        "metadata": {
            "colab": {"name": f"{stem}.ipynb", "provenance": []},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.x"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def validate_notebooks(expected: set[str]) -> None:
    actual = {p.name for p in OUT.glob("*.ipynb")}
    if actual != expected:
        raise RuntimeError(f"Notebook/source mismatch: expected={sorted(expected)}, actual={sorted(actual)}")

    errors: list[str] = []
    for path in sorted(OUT.glob("*.ipynb")):
        try:
            nb = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"{path.name}: invalid JSON: {exc}")
            continue

        if nb.get("nbformat") != 4:
            errors.append(f"{path.name}: nbformat is not 4")

        all_source = "\n".join(
            "".join(cell.get("source", [])) for cell in nb.get("cells", [])
        )
        if "%run " in all_source:
            errors.append(f"{path.name}: contains forbidden %run wrapper")
        if "cp_milp_exact_baselines" in all_source:
            errors.append(f"{path.name}: contains obsolete cp_milp_exact_baselines reference")

        src_name = path.with_suffix(".py").name
        expected_file_line = f"__file__ = r'{REPO_DIR}/src/{src_name}'"
        if expected_file_line not in all_source:
            errors.append(f"{path.name}: missing notebook-safe __file__ definition")

        implementation_cells = [
            cell for cell in nb.get("cells", [])
            if cell.get("cell_type") == "code"
            and any(line.startswith('"""') or line.startswith("from __future__") for line in cell.get("source", []))
        ]
        if not implementation_cells:
            # Some source files begin with comments/imports instead of docstrings/future imports.
            code_cells = [cell for cell in nb.get("cells", []) if cell.get("cell_type") == "code"]
            implementation_cells = code_cells[2:3]
        if len(implementation_cells) != 1:
            errors.append(f"{path.name}: could not identify exactly one implementation cell")
            continue

        source = "".join(implementation_cells[0].get("source", []))
        try:
            compile(source, src_name, "exec")
        except SyntaxError as exc:
            errors.append(f"{path.name}: embedded Python syntax error: {exc}")

    if errors:
        raise RuntimeError("Colab validation failed:\n- " + "\n- ".join(errors))
    print(f"Validated {len(expected)} notebooks: JSON, coverage, __file__, no %run, no cp_milp, syntax OK.")


def main() -> None:
    OUT.mkdir(exist_ok=True)
    expected: set[str] = set()
    for src in sorted(SRC.glob("*.py")):
        dst = OUT / f"{src.stem}.ipynb"
        dst.write_text(json.dumps(notebook_for(src), indent=2) + "\n", encoding="utf-8")
        expected.add(dst.name)
    for old in OUT.glob("*.ipynb"):
        if old.name not in expected:
            old.unlink()
    print(f"Generated {len(expected)} notebook-native Colab notebooks.")
    validate_notebooks(expected)


if __name__ == "__main__":
    main()
