"""Generate camera-ready tables directly from committed result files."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent.parent
RESULT_DIR = PROJECT_DIR / "results" / "multi_instance_m2max"
PRIMARY_CSV = PROJECT_DIR / "results" / "unified_comparison_with_cpsat.csv"
PRIMARY_OUTPUT = PROJECT_DIR / "paper" / "generated_primary_table.tex"
SENSITIVITY_OUTPUT = PROJECT_DIR / "paper" / "generated_sensitivity_table.tex"

CASES = (
    ("primary_6_obstacles", "Primary (6 obs.)"),
    ("random_2_obstacles", "Sensitivity A (2 obs.)"),
    ("random_3_obstacles", "Sensitivity B (3 obs.)"),
)

PRIMARY_METHODS = {
    "A*": ("A*", 1, 3),
    "RRT-best": ("RRT", 40, 4),
    "QUAV-style QAOA": ("QUAV-QAOA", 1, 2),
    "CP-SAT exact": ("CP-SAT exact", 1, 2),
    "HUBO trajectory-SA": ("HUBO-SA", 50, 2),
    "HUBO->QUBO/neal": ("QUBO/\\texttt{neal}", 50, 3),
}


def tex_rate(value: str) -> str:
    return value.replace("%", "\\%")


def render_primary() -> str:
    with PRIMARY_CSV.open(newline="", encoding="utf-8") as stream:
        records = list(csv.DictReader(stream))
    if [record["Method"] for record in records] != list(PRIMARY_METHODS):
        raise ValueError("Primary CSV methods or method order changed")
    rows: list[str] = []
    for record in records:
        label, divisor, decimals = PRIMARY_METHODS[record["Method"]]
        runtime = float(record["Runtime s"]) / divisor
        fields = (
            label,
            tex_rate(record["Feasible"]),
            tex_rate(record["Goal arrival"]),
            tex_rate(record["Full success"]),
            record["Path length"],
            record["Turns"],
            record["Buffer steps"],
            f"{100.0 * float(record['Visibility']):.1f}\\%",
            f"{float(record['Native HUBO energy']):.2f}",
            f"{runtime:.{decimals}f}s",
        )
        rows.append(" & ".join(fields) + "\\\\")
    body = "\n".join(rows)
    return f"""% Generated by src/generate_publication_tables.py; do not edit manually.
\\begin{{table*}}[t]
\\centering
\\small
\\begin{{tabular*}}{{\\textwidth}}{{@{{\\extracolsep{{\\fill}}}}lccccccccc@{{}}}}
\\toprule
Method & Feas. & Goal & Full & Len. & Turns & Buf. & Vis. & HUBO E & Time/run\\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular*}}
\\caption{{Unified same-platform comparison on the primary instance. Yes/no is a single output; percentages use 50 runs/reads. SA reports its best full-success path; \\texttt{{neal}} reports its best-energy feasible non-goal sample. Time/run is mean wall-clock time; the \\texttt{{neal}} value is amortized over one 50-read batch. Only \\texttt{{neal}} samples the full penalized QUBO; the other methods construct or enforce some or all feasibility conditions before scoring.}}
\\label{{tab:unified}}
\\end{{table*}}
"""


def load_case(name: str) -> dict:
    path = RESULT_DIR / f"{name}.json"
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)


def rate_cell(method: dict, metric: str) -> str:
    rate = float(method[f"{metric}_rate"])
    lower, upper = method["wilson_95"][metric]
    lower = max(0.0, float(lower))
    upper = min(1.0, float(upper))
    return f"{100.0 * rate:.1f}\\% [{100.0 * lower:.1f}--{100.0 * upper:.1f}]"


def energy_cell(method: dict) -> str:
    return f"{float(method['hubo_energy']):.2f}"


def render_sensitivity() -> str:
    rows: list[str] = []
    for name, label in CASES:
        case = load_case(name)
        methods = case["methods"]
        sa = methods["HUBO trajectory-SA"]
        neal = methods["HUBO->QUBO/neal"]
        cpsat = methods["CP-SAT exact"]
        if case.get("case") != name:
            raise ValueError(f"Case-name mismatch in {name}.json")
        if case["details"]["trajectory_sa"]["sample_count"] != 50:
            raise ValueError(f"Expected 50 SA runs for {name}")
        if case["details"]["neal"]["sample_count"] != 50:
            raise ValueError(f"Expected 50 neal reads for {name}")
        if not cpsat.get("is_optimal") or cpsat.get("status") != "OPTIMAL":
            raise ValueError(f"CP-SAT did not certify OPTIMAL for {name}")
        rows.extend(
            (
                f"{label} & SA & {rate_cell(sa, 'feasible')} & {rate_cell(sa, 'goal')} & {rate_cell(sa, 'full')} & {energy_cell(sa)}\\\\",
                f" & \\texttt{{neal}} & {rate_cell(neal, 'feasible')} & {rate_cell(neal, 'goal')} & {rate_cell(neal, 'full')} & {energy_cell(neal)}\\\\",
                f" & CP-SAT (OPT.) & Yes & Yes & Yes & {energy_cell(cpsat)}\\\\",
                "\\addlinespace",
            )
        )
    rows.pop()
    body = "\n".join(rows)
    return f"""% Generated by src/generate_publication_tables.py; do not edit manually.
\\begin{{table*}}[t]
\\centering
\\scriptsize
\\begin{{tabular*}}{{\\textwidth}}{{@{{\\extracolsep{{\\fill}}}}llcccc@{{}}}}
\\toprule
Instance & Method & Feas. & Goal & Full & HUBO E\\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular*}}
\\caption{{Three-instance sensitivity results. Stochastic cells give the observed percentage and 95\\% Wilson interval over 50 fixed-seed runs or reads. SA reports its best full-success energy; \\texttt{{neal}} reports its best-energy feasible sample; CP-SAT reports a single OPTIMAL output for the integer-scaled model. HUBO E omits the common constant 21,000.}}
\\label{{tab:sensitivity}}
\\end{{table*}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        PRIMARY_OUTPUT: render_primary(),
        SENSITIVITY_OUTPUT: render_sensitivity(),
    }
    if args.check:
        for path, generated in outputs.items():
            if path.read_text(encoding="utf-8") != generated:
                raise SystemExit(f"{path} is not synchronized with result data")
            print(f"Verified {path.relative_to(PROJECT_DIR)}")
        return
    for path, generated in outputs.items():
        path.write_text(generated, encoding="utf-8")
        print(f"Wrote {path.relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
